// admin/src/app/types.ts
export enum Role {
  ADMINISTRADOR = 'administrador',
  RECEPCIONISTA = 'recepcionista',
  CORTADOR = 'cortador',
  DISEÑADOR = 'diseñador',
  REPRESENTANTE_TALLER = 'representante_taller',
  AYUDANTE = 'ayudante',
}

export enum Permission {
  // Usuarios
  VIEW_USUARIOS = 'VIEW_USUARIOS',
  MANAGE_USUARIOS = 'MANAGE_USUARIOS',
  
  // Productos
  VIEW_PRODUCTOS = 'VIEW_PRODUCTOS',
  MANAGE_PRODUCTOS = 'MANAGE_PRODUCTOS',
  
  // Dashboard
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  
  // Inventario
  VIEW_INVENTARIO = 'VIEW_INVENTARIO',
  MANAGE_INVENTARIO = 'MANAGE_INVENTARIO',
  REGISTER_USO_MATERIALES = 'REGISTER_USO_MATERIALES',
  
  // Reportes
  VIEW_REPORTES = 'VIEW_REPORTES',
  GENERATE_REPORTES = 'GENERATE_REPORTES',
  
  // Pagos
  VIEW_PAGOS = 'VIEW_PAGOS',
  MANAGE_PAGOS = 'MANAGE_PAGOS',
  
  // Pedidos (NO órdenes)
  VIEW_PEDIDOS = 'VIEW_PEDIDOS',
  MANAGE_PEDIDOS = 'MANAGE_PEDIDOS',
  
  // Ventas
  VIEW_VENTAS = 'VIEW_VENTAS',
  MANAGE_VENTAS = 'MANAGE_VENTAS',
  
  // Cotizaciones
  VIEW_COTIZACIONES = 'VIEW_COTIZACIONES',
  MANAGE_COTIZACIONES = 'MANAGE_COTIZACIONES',
  
  // Clientes
  VIEW_CLIENTES = 'VIEW_CLIENTES',
  MANAGE_CLIENTES = 'MANAGE_CLIENTES',
  
  // Talleres
  VIEW_TALLERES = 'VIEW_TALLERES',
  MANAGE_TALLERES = 'MANAGE_TALLERES',
  UPDATE_ESTADO_TALLER = 'UPDATE_ESTADO_TALLER',
  
  // Confecciones
  VIEW_CONFECCIONES = 'VIEW_CONFECCIONES',
  MANAGE_CONFECCIONES = 'MANAGE_CONFECCIONES',
  
  // Despacho
  VIEW_DESPACHO = 'VIEW_DESPACHO',
  CONFIRM_ENTREGA = 'CONFIRM_ENTREGA',
  UPDATE_ESTADO_DESPACHO = 'UPDATE_ESTADO_DESPACHO',
}