export enum Role {
  ADMINISTRADOR = 'ADMINISTRADOR',
  RECEPCIONISTA = 'RECEPCIONISTA',
  CORTADOR = 'CORTADOR',
  DISEÑADOR = 'DISEÑADOR',
  REPRESENTANTE_TALLER = 'REPRESENTANTE_TALLER',
  AYUDANTE = 'AYUDANTE'
}

export enum Permission {
  // Gestión de Usuarios
  VIEW_USUARIOS = 'VIEW_USUARIOS',
  MANAGE_USUARIOS = 'MANAGE_USUARIOS',
  
  // Gestión de Productos
  VIEW_PRODUCTOS = 'VIEW_PRODUCTOS',
  MANAGE_PRODUCTOS = 'MANAGE_PRODUCTOS',
  
  // Dashboard
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  
  // Gestión de Inventario
  VIEW_INVENTARIO = 'VIEW_INVENTARIO',
  MANAGE_INVENTARIO = 'MANAGE_INVENTARIO',
  REGISTER_USO_MATERIALES = 'REGISTER_USO_MATERIALES',
  
  // Reportes y Notificaciones
  VIEW_REPORTES = 'VIEW_REPORTES',
  GENERATE_REPORTES = 'GENERATE_REPORTES',
  
  // Gestión de Pagos
  VIEW_PAGOS = 'VIEW_PAGOS',
  MANAGE_PAGOS = 'MANAGE_PAGOS',
  
  // Gestión de Órdenes/Pedidos
  VIEW_ORDENES = 'VIEW_ORDENES',
  MANAGE_ORDENES = 'MANAGE_ORDENES',
  
  // Gestión de Ventas
  VIEW_VENTAS = 'VIEW_VENTAS',
  MANAGE_VENTAS = 'MANAGE_VENTAS',
  
  // Gestión de Cotizaciones (Prices)
  VIEW_COTIZACIONES = 'VIEW_COTIZACIONES',
  MANAGE_COTIZACIONES = 'MANAGE_COTIZACIONES',
  
  // Talleres Externos
  VIEW_TALLERES = 'VIEW_TALLERES',
  MANAGE_TALLERES = 'MANAGE_TALLERES',
  UPDATE_ESTADO_TALLER = 'UPDATE_ESTADO_TALLER',
  
  // Confecciones
  VIEW_CONFECCIONES = 'VIEW_CONFECCIONES',
  MANAGE_CONFECCIONES = 'MANAGE_CONFECCIONES',
  
  // Despacho de Pedidos
  VIEW_DESPACHO = 'VIEW_DESPACHO',
  CONFIRM_ENTREGA = 'CONFIRM_ENTREGA',
  UPDATE_ESTADO_DESPACHO = 'UPDATE_ESTADO_DESPACHO'
}