import { Product } from '@/types/product';

// Datos de ejemplo de productos de ropa femenina con precios mayoristas
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Blusa de seda premium',
    description: 'Blusa elegante de seda natural, perfecta para ocasiones especiales',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&h=500&fit=crop',
    category: 'blusas',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Negro', 'Blanco', 'Rosa', 'Azul'],
    rating: 4.5,
    reviews: 24,
    inStock: true,
  },
  {
    id: '2',
    name: 'Jeans clásicos azul',
    description: 'Jeans ajustados con stretch, cómodos y versátiles',
    price: 22.90,
    image: 'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=500&h=500&fit=crop',
    category: 'pantalones',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Azul oscuro', 'Azul claro', 'Negro'],
    rating: 4.8,
    reviews: 45,
    inStock: true,
  },
  {
    id: '3',
    name: 'Vestido floral elegante',
    description: 'Vestido midi con estampado floral, ideal para salidas',
    price: 24.50,
    image: 'https://images.unsplash.com/photo-1612336307429-8a88e8d08dbb?w=500&h=500&fit=crop',
    category: 'vestidos',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Rosa', 'Azul', 'Verde'],
    rating: 4.3,
    reviews: 18,
    inStock: true,
  },
  {
    id: '4',
    name: 'Chaqueta de cuero',
    description: 'Chaqueta de cuero auténtico, estilo casual',
    price: 29.90,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=500&h=500&fit=crop',
    category: 'chaquetas',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Negro', 'Marrón', 'Rojo'],
    rating: 4.6,
    reviews: 32,
    inStock: true,
  },
  {
    id: '5',
    name: 'Falda plisada midi',
    description: 'Falda elegante con pliegues, perfecta para el trabajo',
    price: 16.90,
    image: 'https://images.unsplash.com/photo-1515662121892-6461fa79ea48?w=500&h=500&fit=crop',
    category: 'faldas',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Negro', 'Gris', 'Beige'],
    rating: 4.4,
    reviews: 21,
    inStock: true,
  },
  {
    id: '6',
    name: 'Top deportivo',
    description: 'Top cómodo para entrenamiento y actividades deportivas',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=500&h=500&fit=crop',
    category: 'deportivo',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Negro', 'Blanco', 'Gris'],
    rating: 4.7,
    reviews: 56,
    inStock: true,
  },
  {
    id: '7',
    name: 'Cardigan de lana',
    description: 'Cardigan suave y cálido para días fríos',
    price: 20.50,
    image: 'https://images.unsplash.com/photo-1556306534-0011253c8925?w=500&h=500&fit=crop',
    category: 'suéteres',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Crema', 'Gris', 'Negro', 'Bordo'],
    rating: 4.5,
    reviews: 28,
    inStock: true,
  },
  {
    id: '8',
    name: 'Leggings premium',
    description: 'Leggings de alta calidad con efecto compresión',
    price: 14.90,
    image: 'https://images.unsplash.com/photo-1544707267537-b997cda8d8d9?w=500&h=500&fit=crop',
    category: 'pantalones',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Negro', 'Gris', 'Azul marino'],
    rating: 4.6,
    reviews: 39,
    inStock: true,
  },
  {
    id: '9',
    name: 'Camiseta básica',
    description: 'Camiseta básica de algodón 100%, perfecta para combinar',
    price: 9.90,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    category: 'blusas',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Blanco', 'Negro', 'Gris'],
    rating: 4.4,
    reviews: 67,
    inStock: true,
  },
  {
    id: '10',
    name: 'Shorts deportivos',
    description: 'Shorts cómodos para entrenamientos intensos',
    price: 13.50,
    image: 'https://images.unsplash.com/photo-1506629082632-7f9a0a7b3f8d?w=500&h=500&fit=crop',
    category: 'pantalones',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Negro', 'Rosado', 'Gris'],
    rating: 4.5,
    reviews: 43,
    inStock: true,
  },
  {
    id: '11',
    name: 'Blusa floral estampada',
    description: 'Blusa con estampado floral, ideal para el verano',
    price: 15.90,
    image: 'https://images.unsplash.com/photo-1506629082632-7f9a0a7b3f8d?w=500&h=500&fit=crop',
    category: 'blusas',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Multicolor', 'Blanco', 'Azul'],
    rating: 4.3,
    reviews: 31,
    inStock: true,
  },
  {
    id: '12',
    name: 'Pantalón elegante',
    description: 'Pantalón de tela elegante, perfecto para oficina',
    price: 21.50,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    category: 'pantalones',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    color: ['Negro', 'Gris oscuro', 'Beige'],
    rating: 4.6,
    reviews: 52,
    inStock: true,
  },
];

export const categories = [
  { id: 'todos', name: 'Todos' },
  { id: 'blusas', name: 'Blusas' },
  { id: 'pantalones', name: 'Pantalones' },
  { id: 'vestidos', name: 'Vestidos' },
  { id: 'chaquetas', name: 'Chaquetas' },
  { id: 'faldas', name: 'Faldas' },
  { id: 'deportivo', name: 'Deportivo' },
  { id: 'suéteres', name: 'Suéteres' },
];
